"""Pin the citation-graph helpers + xref_explore planner +
xref_explore router intent.
"""
from __future__ import annotations

import pytest

from book.ir import Book, BookNode, CrossRef
from book import xref


def _book_with_xrefs() -> Book:
    """Tiny book mimicking ESLII's chapter-section layout with a
    deterministic citation graph."""
    root = BookNode(nid="b", kind="book", number=None,
                    title="ESL", page_start=1, page_end=999)
    ch3 = BookNode(nid="b/ch3", kind="chapter", number="3",
                   title="Linear Methods for Regression",
                   page_start=40, page_end=80)
    ch5 = BookNode(nid="b/ch5", kind="chapter", number="5",
                   title="Basis Expansions and Regularization",
                   page_start=100, page_end=200)
    s5_8 = BookNode(nid="b/ch5/s5_8", kind="section", number="5.8",
                    title="Reproducing Kernel Hilbert Spaces",
                    page_start=170, page_end=190)
    ss5_8_1 = BookNode(nid="b/ch5/s5_8/ss5_8_1", kind="subsection",
                       number="5.8.1", title="Spaces of Functions Generated by Kernels",
                       page_start=171, page_end=175)
    s5_8.children.append(ss5_8_1)
    ch5.children.append(s5_8)
    ch12 = BookNode(nid="b/ch12", kind="chapter", number="12",
                    title="Support Vector Machines",
                    page_start=400, page_end=440)
    s12_3 = BookNode(nid="b/ch12/s12_3", kind="section", number="12.3",
                     title="Support Vector Machines and Kernels",
                     page_start=420, page_end=430)
    ch12.children.append(s12_3)
    root.children.extend([ch3, ch5, ch12])

    # Hand-rolled citation graph:
    #   ch3 → ch5  (Chapter 5)
    #   ch5/s5_8 → ch12 (Chapter 12, twice)
    #   ch5/s5_8 → b/ch5/s5_8/ss5_8_1  (intra-subtree, should be filtered)
    #   ss5_8_1 → ch5/s5_8 (intra-subtree, should be filtered)
    #   ch12 → ch5/s5_8 (Section 5.8) — incoming from outside subtree
    #   ch12/s12_3 → ch5/s5_8 — incoming from outside subtree
    crs = [
        CrossRef(from_nid="b/ch3", to_nid="b/ch5",
                 label="Chapter 5", char_offset=0),
        CrossRef(from_nid="b/ch5/s5_8", to_nid="b/ch12",
                 label="Chapter 12", char_offset=10),
        CrossRef(from_nid="b/ch5/s5_8", to_nid="b/ch12",
                 label="Chapter 12", char_offset=400),
        CrossRef(from_nid="b/ch5/s5_8", to_nid="b/ch5/s5_8/ss5_8_1",
                 label="Section 5.8.1", char_offset=200),
        CrossRef(from_nid="b/ch5/s5_8/ss5_8_1", to_nid="b/ch5/s5_8",
                 label="Section 5.8", char_offset=50),
        CrossRef(from_nid="b/ch12", to_nid="b/ch5/s5_8",
                 label="Section 5.8", char_offset=20),
        CrossRef(from_nid="b/ch12/s12_3", to_nid="b/ch5/s5_8",
                 label="Section 5.8", char_offset=30),
    ]
    return Book(title="ESL", author=None, source="", root=root,
                concepts={}, pages=[], figures=[], cross_refs=crs)


# ---------------------------------------------------------------------------
# Outgoing / incoming
# ---------------------------------------------------------------------------

def test_outgoing_from_section_includes_descendants():
    book = _book_with_xrefs()
    refs = xref.outgoing(book, "b/ch5")
    # ch5 has no direct outgoing, but its descendant s5_8 has 2.
    targets = [cr.to_nid for cr in refs]
    assert "b/ch12" in targets


def test_outgoing_drops_self_subtree_refs():
    book = _book_with_xrefs()
    refs = xref.outgoing(book, "b/ch5/s5_8")
    # ch5/s5_8 → ss5_8_1 is intra-subtree.
    for cr in refs:
        assert cr.to_nid != "b/ch5/s5_8/ss5_8_1"


def test_incoming_drops_intra_subtree():
    book = _book_with_xrefs()
    refs = xref.incoming(book, "b/ch5/s5_8")
    # Only the ch12 + ch12/s12_3 references are external.
    sources = [cr.from_nid for cr in refs]
    assert "b/ch5/s5_8/ss5_8_1" not in sources
    assert "b/ch12" in sources
    assert "b/ch12/s12_3" in sources


def test_incoming_can_disable_filter():
    """Disabling both filters surfaces every raw incoming ref."""
    book = _book_with_xrefs()
    refs = xref.incoming(
        book, "b/ch5/s5_8",
        drop_intra_subtree=False, drop_self_refs=False,
    )
    sources = [cr.from_nid for cr in refs]
    assert "b/ch5/s5_8/ss5_8_1" in sources


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------

def test_group_by_label_counts():
    book = _book_with_xrefs()
    refs = xref.outgoing(book, "b/ch5/s5_8")
    grouped = xref.group_by_label(refs)
    # "Chapter 12" appears twice in the fixture.
    assert grouped[0] == ("Chapter 12", 2)


def test_group_by_source_for_incoming():
    book = _book_with_xrefs()
    refs = xref.incoming(book, "b/ch5/s5_8")
    sources = [nid for nid, _, _ in xref.group_by_source(refs)]
    assert sources[:2] == sorted(["b/ch12", "b/ch12/s12_3"])
    # Each source contributes 1 ref in the fixture.
    counts = [c for _, c, _ in xref.group_by_source(refs)]
    assert counts == [1, 1]


def test_most_cited_orders_by_count():
    book = _book_with_xrefs()
    top = xref.most_cited(book, k=3)
    # b/ch5/s5_8 has 3 incoming (after self-ref filter).
    nids = [n for n, _ in top]
    assert "b/ch5/s5_8" in nids
    counts = dict(top)
    assert counts["b/ch5/s5_8"] >= 2


# ---------------------------------------------------------------------------
# Citation path
# ---------------------------------------------------------------------------

def test_citation_path_finds_two_hop():
    book = _book_with_xrefs()
    path = xref.citation_path(book, "b/ch3", "b/ch12", max_hops=3)
    # ch3 → ch5 → ch12 takes two hops.
    assert len(path) == 2
    assert path[0].to_nid == "b/ch5"
    assert path[1].from_nid in {"b/ch5", "b/ch5/s5_8"}


def test_citation_path_finds_subtree_containment():
    """When the target sits inside a node we can already reach, the
    path stops at the containing ancestor — the cited chapter
    contains the target subsection, so 1 hop is enough."""
    book = _book_with_xrefs()
    path = xref.citation_path(book, "b/ch3", "b/ch5/s5_8/ss5_8_1",
                              max_hops=1)
    assert len(path) == 1
    assert path[0].from_nid == "b/ch3"
    assert path[0].to_nid == "b/ch5"


def test_citation_path_returns_empty_when_unreachable():
    """No edges at all from a leaf with nothing cited."""
    book = _book_with_xrefs()
    path = xref.citation_path(book, "b/ch5/s5_8/ss5_8_1", "b/ch3",
                              max_hops=2)
    assert path == []


# ---------------------------------------------------------------------------
# qa.xref_explore planner
# ---------------------------------------------------------------------------

def test_xref_explore_plan_has_both_directions():
    from narrator.qa import xref_explore
    book = _book_with_xrefs()
    plan = xref_explore(book, "b/ch5/s5_8")
    assert plan.meta["mode"] == "xref_explore"
    assert plan.meta["focus_nid"] == "b/ch5/s5_8"
    text = " ".join(c.text for c in plan.clauses)
    assert "references" in text.lower()
    assert "cited" in text.lower()
    # Outgoing labels in narration.
    assert "Chapter 12" in text


def test_xref_explore_handles_unknown_nid():
    from narrator.qa import xref_explore
    book = _book_with_xrefs()
    plan = xref_explore(book, "b/nonsense")
    assert any("focus" in c.text.lower() or "ask me" in c.text.lower()
               for c in plan.clauses)


def test_xref_explore_handles_missing_outgoing():
    """Section that cites nothing should still produce a sensible plan."""
    from narrator.qa import xref_explore
    book = _book_with_xrefs()
    plan = xref_explore(book, "b/ch3")
    text = " ".join(c.text for c in plan.clauses)
    # ch3 → ch5 is the only outgoing; cited by nothing in the
    # fixture.  Plan should mention this gracefully.
    assert "cite" in text.lower() or "citation" in text.lower() or "no" in text.lower()


# ---------------------------------------------------------------------------
# Router
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("utterance", [
    "see also",
    "what else references this",
    "related sections",
    "where else is this used",
    "citation graph",
    "cross references",
])
def test_router_classifies_xref_explore(utterance):
    from narrator import router
    r = router.route(
        utterance,
        last_focus_nid="b/ch5/s5_8",
        last_focus_topic="reproducing kernels",
    )
    assert r.intent == router.INTENT_XREF_EXPLORE
    assert r.target_nid == "b/ch5/s5_8"


def test_router_xref_explore_without_focus():
    """No focus → still classifies; Session.ask falls back to QA."""
    from narrator import router
    r = router.route("see also")
    assert r.intent == router.INTENT_XREF_EXPLORE
    assert r.target_nid == ""
