"""Regression tests for the book-figure relevance filter.

Books occasionally contain figures with no captions (covers, parodies,
PDF-extraction artifacts).  ESLII p.186 has a yellow Scream painting
inside §5.8.1 "Spaces of Functions Generated by Kernels"; the strict
in-scope policy used to surface it for "what is a functional".

Q&A streams now pre-filter book figures by embedding-cosine against
the question.  These tests exercise the routing path with stub
embeddings so we don't depend on the live server.
"""
from __future__ import annotations

import pytest

from book.ir import Book, BookNode, FigureRef
from serve.orchestrator import _figure_relevance


def _toy_book(*figures: FigureRef) -> Book:
    chapters = [
        BookNode(
            nid="b/ch5", kind="chapter", number="5", title="Bases",
            page_start=140, page_end=200,
            children=[
                BookNode(
                    nid="b/ch5/s5_8", kind="section", number="5.8",
                    title="Spaces of Functions Generated by Kernels",
                    page_start=180, page_end=200,
                    body_text=(
                        "A reproducing kernel Hilbert space H_K is the "
                        "completion of the span of K(x, ·) over the data."
                    ),
                ),
            ],
        ),
    ]
    root = BookNode(
        nid="b", kind="book", number=None, title="Test",
        page_start=1, page_end=300, children=chapters,
    )
    return Book(
        title="Test", author=None, source="", root=root,
        concepts={}, pages=[], figures=list(figures),
    )


def test_relevance_uses_caption_when_present(monkeypatch):
    """A captioned figure compares its caption to the question."""
    fig = FigureRef(
        fid="real_fig", home_nid="b/ch5/s5_8",
        page=190, caption="A reproducing kernel Hilbert space.",
        bbox=(0, 0, 100, 100), image_path="real.png",
    )
    book = _toy_book(fig)

    captured: list[str] = []
    from book import embeddings as _emb_mod
    monkeypatch.setattr(_emb_mod, "is_available", lambda: True)
    monkeypatch.setattr(_emb_mod, "embed_text",
                        lambda t: (captured.append(t) or (1.0, 0.0)))
    monkeypatch.setattr(_emb_mod, "cosine",
                        lambda a, b: sum(x * y for x, y in zip(a, b)))
    score, anchor = _figure_relevance(book, fig, (1.0, 0.0))
    assert anchor == "caption"
    assert score == pytest.approx(1.0)
    assert captured == ["A reproducing kernel Hilbert space."]


def test_relevance_falls_back_to_passage_body_when_caption_empty(monkeypatch):
    """An empty-caption figure scores against its owning passage."""
    fig = FigureRef(
        fid="scream", home_nid="b/ch5/s5_8",
        page=186, caption="",
        bbox=(0, 0, 100, 100), image_path="scream.png",
    )
    book = _toy_book(fig)

    captured: list[str] = []
    from book import embeddings as _emb_mod
    monkeypatch.setattr(_emb_mod, "is_available", lambda: True)
    monkeypatch.setattr(_emb_mod, "embed_text",
                        lambda t: (captured.append(t) or (0.5, 0.5)))
    monkeypatch.setattr(_emb_mod, "cosine",
                        lambda a, b: sum(x * y for x, y in zip(a, b)))
    score, anchor = _figure_relevance(book, fig, (0.5, 0.5))
    assert anchor == "passage_body"
    # The passage body was embedded (verifies fallback path).
    assert any("reproducing kernel Hilbert space" in t for t in captured)
    assert 0.0 < score <= 1.0


def test_relevance_returns_zero_when_embeddings_offline(monkeypatch):
    """When the embedding server is down, score is 0 and we don't filter."""
    fig = FigureRef(
        fid="x", home_nid="b/ch5/s5_8",
        page=190, caption="anything",
        bbox=(0, 0, 100, 100), image_path="x.png",
    )
    book = _toy_book(fig)

    from book import embeddings as _emb_mod
    monkeypatch.setattr(_emb_mod, "is_available", lambda: False)
    score, anchor = _figure_relevance(book, fig, (1.0,))
    assert score == 0.0
    assert "unreachable" in anchor


def test_low_relevance_filters_out_irrelevant_figure():
    """End-to-end: a figure scoring below threshold is dropped."""
    from serve.orchestrator import (
        FIGURE_RELEVANCE_THRESHOLD, Orchestrator,
    )
    from chalkboard import Chalkboard
    from narrator import NarrationPlan, NarrationClause
    from narrator.tts import NullTTS

    fig_relevant = FigureRef(
        fid="rel", home_nid="b/ch5/s5_8",
        page=190, caption="The reproducing kernel Hilbert space.",
        bbox=(0, 0, 100, 100), image_path="rel.png",
    )
    fig_irrelevant = FigureRef(
        fid="scream", home_nid="b/ch5/s5_8",
        page=186, caption="",
        bbox=(0, 0, 100, 100), image_path="scream.png",
    )
    book = _toy_book(fig_relevant, fig_irrelevant)

    plan = NarrationPlan(
        topic="Q: what is a functional",
        book_title="Test",
        clauses=[
            NarrationClause(
                text="A functional is a function from a function space to R.",
                home_nid="b/ch5/s5_8",
                concepts=[], suggested_dur=2.0,
            ),
        ],
        visited_nids=["b/ch5/s5_8"],
        meta={"mode": "tangent",
              "question": "what is a functional"},
    )

    orch = Orchestrator(
        book=book, plan=plan, chalkboard=Chalkboard(),
        tts=NullTTS(),
    )

    # Force a controlled embedding scoring: relevant gets 0.9, scream 0.1.
    def _stub_relevance(book, fig, qv):
        if fig.fid == "rel":
            return 0.9, "caption"
        return 0.1, "passage_body"

    import serve.orchestrator as orc_mod
    orig = orc_mod._figure_relevance
    orc_mod._figure_relevance = _stub_relevance
    try:
        # Bypass embed_text init — pretend we have a query vec.
        orch._query_vec = (1.0,)
        orch._query_vec_loaded = True
        figs = [fig_relevant, fig_irrelevant]
        kept = orch._filter_figures_by_relevance(figs)
    finally:
        orc_mod._figure_relevance = orig

    assert len(kept) == 1
    assert kept[0].fid == "rel"
    assert getattr(kept[0], "_relevance_score") >= FIGURE_RELEVANCE_THRESHOLD
