"""Pin the question router's intent classification + nid resolution.

Router is rule-based; tests pin canonical phrasings so the
classifier never silently regresses on the high-traffic intents
(book / chapter / section / follow-up / control / topic-qa).
"""
from __future__ import annotations

import pytest

from book.ir import Book, BookNode
from narrator import router


def _mini_book() -> Book:
    """Tiny tree mimicking ESLII's chapter-section layout."""
    root = BookNode(nid="b", kind="book", number=None, title="ESL",
                    page_start=1, page_end=999)
    ch5 = BookNode(nid="b/ch5", kind="chapter", number="5",
                   title="Basis Expansions and Regularization",
                   page_start=100, page_end=200)
    ch5_8 = BookNode(nid="b/ch5/s5_8", kind="section", number="5.8",
                     title="Regularization and Reproducing Kernel Hilbert Spaces",
                     page_start=170, page_end=190)
    ch5_8_1 = BookNode(nid="b/ch5/s5_8/ss5_8_1", kind="subsection",
                       number="5.8.1",
                       title="Spaces of Functions Generated by Kernels",
                       page_start=171, page_end=175)
    ch5_8.children.append(ch5_8_1)
    ch5.children.append(ch5_8)
    ch3 = BookNode(nid="b/ch3", kind="chapter", number="3",
                   title="Linear Methods for Regression",
                   page_start=40, page_end=80)
    root.children.extend([ch3, ch5])
    return Book(title="ESL", author=None, source="", root=root,
                concepts={}, pages=[], figures=[])


# ---------------------------------------------------------------------------
# Classification
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("utterance", [
    "what is this book about",
    "What is this book about?",
    "summarise the book",
    "summarize the book",
    "tell me about this book",
    "give me a book overview",
])
def test_routes_book_overview(utterance):
    r = router.route(utterance, book=_mini_book())
    assert r.intent == router.INTENT_BOOK_OVERVIEW


@pytest.mark.parametrize("utterance,expected_nid", [
    ("explain chapter 5", "b/ch5"),
    ("what is chapter 3 about", "b/ch3"),
    ("Chapter 5 please", "b/ch5"),
])
def test_routes_chapter_overview(utterance, expected_nid):
    r = router.route(utterance, book=_mini_book())
    assert r.intent == router.INTENT_CHAPTER_OVERVIEW
    assert r.target_nid == expected_nid


@pytest.mark.parametrize("utterance,expected_nid", [
    ("explain section 5.8", "b/ch5/s5_8"),
    ("§5.8.1", "b/ch5/s5_8/ss5_8_1"),
    ("tell me about 5.8.1", "b/ch5/s5_8/ss5_8_1"),
])
def test_routes_section_overview(utterance, expected_nid):
    r = router.route(utterance, book=_mini_book())
    assert r.intent == router.INTENT_SECTION_OVERVIEW
    assert r.target_nid == expected_nid


@pytest.mark.parametrize("utterance,expected_action", [
    ("pause", "pause"),
    ("Please pause.", "pause"),
    ("stop", "stop"),
    ("cancel", "stop"),
    ("resume", "resume"),
    ("unpause", "resume"),
    ("speed up", "fast"),
    ("slow down", "slow"),
])
def test_routes_control_with_action(utterance, expected_action):
    r = router.route(utterance)
    assert r.intent == router.INTENT_CONTROL
    assert r.control_action == expected_action


@pytest.mark.parametrize("utterance", [
    "tell me more",
    "more about that",
    "go deeper",
    "Continue.",
    "more",
    "deeper",
])
def test_routes_follow_up(utterance):
    r = router.route(
        utterance,
        last_focus_nid="b/ch5/s5_8/ss5_8_1",
        last_focus_topic="regularization",
    )
    assert r.intent == router.INTENT_FOLLOW_UP
    assert r.topic == "regularization"
    assert r.target_nid == "b/ch5/s5_8/ss5_8_1"


def test_topic_qa_default():
    r = router.route("what is bagging", book=_mini_book())
    assert r.intent == router.INTENT_TOPIC_QA
    assert r.topic == "what is bagging"


def test_depth_modifier_extracted():
    r = router.route("explain chapter 5 in detail", book=_mini_book())
    assert r.intent == router.INTENT_CHAPTER_OVERVIEW
    assert r.depth == "deep"

    r2 = router.route("short answer please")
    assert r2.depth == "short"


def test_unknown_chapter_number_target_empty():
    """Chapter 99 doesn't exist — intent still chapter_overview but
    target_nid empty so the session falls back to topic_qa."""
    r = router.route("explain chapter 99", book=_mini_book())
    assert r.intent == router.INTENT_CHAPTER_OVERVIEW
    assert r.target_nid == ""


def test_empty_utterance_topic_qa():
    r = router.route("")
    assert r.intent == router.INTENT_TOPIC_QA


# ---------------------------------------------------------------------------
# Recap / reshow / forget
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("utterance", [
    "what have we covered",
    "what did you cover so far",
    "recap",
    "recap so far",
    "summarise what we discussed",
    "where are we so far",
])
def test_recap_intent(utterance):
    r = router.route(utterance, book=_mini_book())
    assert r.intent == router.INTENT_RECAP


@pytest.mark.parametrize("utterance,expected_topic", [
    ("show me regularization again", "regularization"),
    ("explain ridge regression again", "ridge regression"),
    ("repeat that", ""),
    ("once more", ""),
    ("again", ""),
])
def test_reshow_intent(utterance, expected_topic):
    r = router.route(
        utterance, book=_mini_book(),
        last_focus_topic="ridge",
    )
    assert r.intent == router.INTENT_RESHOW
    if expected_topic:
        assert expected_topic.lower() in r.topic.lower()
    else:
        # Bare reshow falls back to last_focus_topic.
        assert r.topic == "ridge"


@pytest.mark.parametrize("utterance,expected_action", [
    ("forget that", "forget"),
    ("forget everything", "forget"),
    ("start fresh", "forget"),
    ("reset", "forget"),
    ("clear what we covered", "forget"),
])
def test_forget_intent(utterance, expected_action):
    r = router.route(utterance)
    assert r.intent == router.INTENT_CONTROL
    assert r.control_action == expected_action
